language: node_js
node_js: 8

install:
  - npm install

script:
  - npx nps build
  - npx nps test.coverage -- -- --silent

after_success:
  - npm install codacy-coverage
  - npx codacy-coverage -v < ./coverage/lcov.info

cache:
  directories
    - node_modules
